Import the numpy module

In [1]:
import numpy as np

Create a 1d numpy array called arr1 that looks like the one below. Display it.

In [2]:
arr1 = np.arange(4, 24, 4)
arr1

array([ 4,  8, 12, 16, 20])

Print out the 3rd element of the array.

In [3]:
arr1[2]

12

Create a 2d numpy array called arr2 that looks like the one below. Display it.

In [4]:
arr2 = np.array([np.random.randint(2, 7, 3), np.random.randint(3, 10, 3), np.random.randint(4, 13, 3)])
print(arr2)

[[5 2 2]
 [3 6 7]
 [9 6 4]]


Print out the element at row=3,col=2.

In [5]:
arr2[2, 1]

6

Create an array that goes from 0 to 100 with step=3. Display it.

In [6]:
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Create a 10x5 2d array filled with zeroes. Display it.

In [7]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create an array called lin1d, that has 100 data points spaced between 57 and 108. Display it.

In [8]:
lin1d = np.linspace(57, 108, 100)
lin1d

array([ 57.        ,  57.51515152,  58.03030303,  58.54545455,
        59.06060606,  59.57575758,  60.09090909,  60.60606061,
        61.12121212,  61.63636364,  62.15151515,  62.66666667,
        63.18181818,  63.6969697 ,  64.21212121,  64.72727273,
        65.24242424,  65.75757576,  66.27272727,  66.78787879,
        67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
        69.36363636,  69.87878788,  70.39393939,  70.90909091,
        71.42424242,  71.93939394,  72.45454545,  72.96969697,
        73.48484848,  74.        ,  74.51515152,  75.03030303,
        75.54545455,  76.06060606,  76.57575758,  77.09090909,
        77.60606061,  78.12121212,  78.63636364,  79.15151515,
        79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
        81.72727273,  82.24242424,  82.75757576,  83.27272727,
        83.78787879,  84.3030303 ,  84.81818182,  85.33333333,
        85.84848485,  86.36363636,  86.87878788,  87.39393939,
        87.90909091,  88.42424242,  88.93939394,  89.45

Reshape lin1d to be 10x10 and call it lin2d. Display it.

In [9]:
lin2d = lin1d.reshape(10, 10)
lin2d

array([[ 57.        ,  57.51515152,  58.03030303,  58.54545455,
         59.06060606,  59.57575758,  60.09090909,  60.60606061,
         61.12121212,  61.63636364],
       [ 62.15151515,  62.66666667,  63.18181818,  63.6969697 ,
         64.21212121,  64.72727273,  65.24242424,  65.75757576,
         66.27272727,  66.78787879],
       [ 67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
         69.36363636,  69.87878788,  70.39393939,  70.90909091,
         71.42424242,  71.93939394],
       [ 72.45454545,  72.96969697,  73.48484848,  74.        ,
         74.51515152,  75.03030303,  75.54545455,  76.06060606,
         76.57575758,  77.09090909],
       [ 77.60606061,  78.12121212,  78.63636364,  79.15151515,
         79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
         81.72727273,  82.24242424],
       [ 82.75757576,  83.27272727,  83.78787879,  84.3030303 ,
         84.81818182,  85.33333333,  85.84848485,  86.36363636,
         86.87878788,  87.39393939],
       [ 8

Print out the shape of lin1d and lin2d.

In [10]:
print("lin1d:", lin1d.shape)
print("lin2d:", lin2d.shape)

lin1d: (100,)
lin2d: (10, 10)


Generate a 5x5 array of random numbers called nums. Display it.

In [11]:
nums = np.random.rand(5, 5)
nums = nums * 10
nums

array([[5.51368387, 2.3173619 , 7.85278011, 5.66535782, 9.64825085],
       [9.18365355, 4.72052442, 3.24199189, 0.55907656, 4.00865881],
       [5.17963376, 7.50475505, 3.02822318, 3.84052244, 0.28891027],
       [4.64724904, 0.41837461, 7.49476471, 3.33107583, 1.42769664],
       [2.90222656, 0.75733754, 7.45136294, 9.41282108, 3.54959715]])

Print out the min, max and mean of the nums array.

In [12]:
print("Min:", nums.min())
print("Max:", nums.max())
print("Mean:", nums.mean())

Min: 0.28891026904873107
Max: 9.64825084935238
Mean: 4.557835624021021


Multiple the entire array nums x2 and store it back in nums. Display the result.

In [13]:
nums = nums * 2
nums

array([[11.02736774,  4.6347238 , 15.70556022, 11.33071565, 19.2965017 ],
       [18.3673071 ,  9.44104884,  6.48398378,  1.11815313,  8.01731763],
       [10.35926752, 15.0095101 ,  6.05644636,  7.68104488,  0.57782054],
       [ 9.29449807,  0.83674923, 14.98952942,  6.66215166,  2.85539329],
       [ 5.80445311,  1.51467509, 14.90272589, 18.82564216,  7.0991943 ]])

Select rows 1 to 2 and cols 2 to 3 and display the result.

In [14]:
nums[0:2, 1:3]

array([[ 4.6347238 , 15.70556022],
       [ 9.44104884,  6.48398378]])

Modify that same selection by multiplying it x10, then display the new nums array.

In [15]:
nums[0:2, 1:3] = nums[0:2, 1:3] * 10
nums

array([[ 11.02736774,  46.347238  , 157.05560225,  11.33071565,
         19.2965017 ],
       [ 18.3673071 ,  94.41048842,  64.83983777,   1.11815313,
          8.01731763],
       [ 10.35926752,  15.0095101 ,   6.05644636,   7.68104488,
          0.57782054],
       [  9.29449807,   0.83674923,  14.98952942,   6.66215166,
          2.85539329],
       [  5.80445311,   1.51467509,  14.90272589,  18.82564216,
          7.0991943 ]])

Load 'data9.npy' into a numpy array named 'data'. Display the array.

In [16]:
data = np.load('data9.npy')
data

array([[0.07301979, 0.16473597, 0.81951432, 0.99818186],
       [0.62804768, 0.34424393, 0.58308361, 0.09436134],
       [0.03345196, 0.28866977, 0.36343501, 0.64198102],
       [0.74852967, 0.08606404, 0.10232671, 0.86568091],
       [0.42570996, 0.55892485, 0.7516009 , 0.3855254 ],
       [0.06229575, 0.95342168, 0.89634407, 0.43225468],
       [0.56500264, 0.93069069, 0.90221041, 0.178963  ],
       [0.84182479, 0.36880305, 0.26415286, 0.04403728],
       [0.78829453, 0.94777048, 0.14770364, 0.58350887],
       [0.47231189, 0.00532193, 0.91274993, 0.86889732]])

Find and display the *index value* of the largest number in each *row* of data. 

In [17]:
print(data.argmax(axis = 1))

[3 0 3 3 2 1 1 0 1 2]


Create a four-dimensional column vector with random numbers between 0 and 1, sampled from the uniform distribution. Name it $w$.

In [18]:
w = np.random.rand(4, 1)
print(w)

[[0.33324452]
 [0.24402925]
 [0.97064143]
 [0.6585765 ]]


Calculate the dot products between $w$ and each row of data.

In [19]:
np.matmul(data, w)

array([[1.51736751],
       [0.9214083 ],
       [0.85715024],
       [0.93988521],
       [1.26169246],
       [1.40812395],
       [1.40898341],
       [0.65593185],
       [1.02163106],
       [1.61688232]])

Create a numpy array $u = (1, -1, 0)$ and a numpy array $v = (1, 0, 1)$. Calculate and display the cosine of the angle between them.

In [20]:
u = np.array([1, -1, 0])
v = np.array([1, 0, 1])
u.dot(v)/np.linalg.norm(u)/np.linalg.norm(v)

0.49999999999999994